def on_button_pressed():
    pass
controller.any_button.on_event(ControllerButtonEvent.PRESSED, on_button_pressed)

projectile: Sprite = None
scene.set_background_color(13)
bunny = sprites.create(img("""
        . . 1 1 . . . . 1 1 . . . . . .
        . . 3 1 . . . . 1 3 . . . . . .
        . . 3 1 . . . . 1 3 . . . . . .
        . . 3 1 1 1 1 1 1 3 . . . . . .
        . . . 1 1 1 1 1 1 . . . . . . .
        . . . 1 f 1 1 f 1 1 . . . . . .
        . . . 1 1 1 1 1 1 1 . . . . . .
        . . . 1 1 f f 1 1 1 . . . . . .
        . . . . 1 1 1 1 . . . . . . . .
        . 1 1 . . . 1 . . . 1 1 . . . .
        . 1 1 1 1 1 1 1 1 1 1 1 . . . .
        . 1 1 . . . 1 . . . 1 1 . . . .
        . . . . . . 1 . . . . . . . . .
        . . . . . 1 1 1 1 1 . . . . . .
        . . . . 1 1 . . . 1 . . . . . .
        . . . 1 1 . . . 1 . . . . . . .
        """),
    SpriteKind.player)
bunny.set_position(10, 80)

def on_update_interval():
    global projectile
    projectile = sprites.create_projectile_from_side(img("""
            ........................
            ..........bbbb..........
            ........bbddddbb........
            .......bddbbbbddb.......
            ......bdbbddddbbdb......
            .....bdbbdbbbbdbbdb.....
            .....bdbdbddddbdbdb.....
            .....cdbbdbbbbdbbdc.....
            .....cbdbbddddbbdbc.....
            .....efbddbbbbddbce.....
            .....eeffbddddbccee.....
            .....eeeeffcccceee......
            .....ceeeeeeeeeeee......
            .....ceeeeeeeeeeee......
            .....feeeeeeeeeeee......
            .....cceeeeeeeeeee......
            ......feeeeeeeeeee......
            .....6fceeeeeeeeee6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6666776...
            ..67768e67766777667776..
            ...668ee7768867788666...
            ......ee77eeee77ecee....
            ......ee6eeeeee6eef.....
            """),
        -100,
        0)
    projectile.y = 80
game.on_update_interval(2000, on_update_interval)
