def on_button_pressed():
    if bunny.y >= 80:
        bunny.vy = -200
controller.any_button.on_event(ControllerButtonEvent.PRESSED, on_button_pressed)

def on_on_overlap(sprite, otherSprite):
    game.game_over(False)
sprites.on_overlap(SpriteKind.player, SpriteKind.projectile, on_on_overlap)

log: Sprite = None
log_speed = 0
bunny: Sprite = None
scene.set_background_color(13)
bunny = sprites.create(img("""
        . . 1 1 . . . . 1 1 . . . . . .
        . . 3 1 . . . . 1 3 . . . . . .
        . . 3 1 . . . . 1 3 . . . . . .
        . . 3 1 1 1 1 1 1 3 . . . . . .
        . . . 1 1 1 1 1 1 . . . . . . .
        . . . 1 f 1 1 f 1 1 . . . . . .
        . . . 1 1 1 1 1 1 1 . . . . . .
        . . . 1 1 f f 1 1 1 . . . . . .
        . . . . 1 1 1 1 . . . . . . . .
        . 1 1 . . . 1 . . . 1 1 . . . .
        . 1 1 1 1 1 1 1 1 1 1 1 . . . .
        . 1 1 . . . 1 . . . 1 1 . . . .
        . . . . . . 1 . . . . . . . . .
        . . . . . 1 1 1 1 1 . . . . . .
        . . . . 1 1 . . . 1 . . . . . .
        . . . 1 1 . . . 1 . . . . . . .
        """),
    SpriteKind.player)
bunny.set_position(10, 80)

def on_on_update():
    if bunny.y < 80:
        bunny.ay = 300
    else:
        bunny.ay = 0
        bunny.vy = 0
game.on_update(on_on_update)

def on_update_interval():
    global log_speed, log
    log_speed = -100 - game.runtime() / 250
    log = sprites.create_projectile_from_side(img("""
            ........................
            ..........bbbb..........
            ........bbddddbb........
            .......bddbbbbddb.......
            ......bdbbddddbbdb......
            .....bdbbdbbbbdbbdb.....
            .....bdbdbddddbdbdb.....
            .....cdbbdbbbbdbbdc.....
            .....cbdbbddddbbdbc.....
            .....efbddbbbbddbce.....
            .....eeffbddddbccee.....
            .....eeeeffcccceee......
            .....ceeeeeeeeeeee......
            .....ceeeeeeeeeeee......
            .....feeeeeeeeeeee......
            .....cceeeeeeeeeee......
            ......feeeeeeeeeee......
            .....6fceeeeeeeeee6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6666776...
            ..67768e67766777667776..
            ...668ee7768867788666...
            ......ee77eeee77ecee....
            ......ee6eeeeee6eef.....
            """),
        log_speed,
        0)
    log.y = 80
    info.change_score_by(10)
game.on_update_interval(2000, on_update_interval)
