controller.anyButton.onEvent(ControllerButtonEvent.Pressed, function () {
    if (bunny.y >= 80) {
        bunny.vy = -200
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    game.gameOver(false)
})
let log: Sprite = null
let log_speed = 0
let bunny: Sprite = null
scene.setBackgroundColor(13)
bunny = sprites.create(img`
    . . 1 1 . . . . 1 1 . . . . . . 
    . . 3 1 . . . . 1 3 . . . . . . 
    . . 3 1 . . . . 1 3 . . . . . . 
    . . 3 1 1 1 1 1 1 3 . . . . . . 
    . . . 1 1 1 1 1 1 . . . . . . . 
    . . . 1 f 1 1 f 1 1 . . . . . . 
    . . . 1 1 1 1 1 1 1 . . . . . . 
    . . . 1 1 f f 1 1 1 . . . . . . 
    . . . . 1 1 1 1 . . . . . . . . 
    . 1 1 . . . 1 . . . 1 1 . . . . 
    . 1 1 1 1 1 1 1 1 1 1 1 . . . . 
    . 1 1 . . . 1 . . . 1 1 . . . . 
    . . . . . . 1 . . . . . . . . . 
    . . . . . 1 1 1 1 1 . . . . . . 
    . . . . 1 1 . . . 1 . . . . . . 
    . . . 1 1 . . . 1 . . . . . . . 
    `, SpriteKind.Player)
bunny.setPosition(10, 80)
game.onUpdate(function () {
    if (bunny.y < 80) {
        bunny.ay = 300
    } else {
        bunny.ay = 0
        bunny.vy = 0
    }
})
game.onUpdateInterval(2000, function () {
    log_speed = -100 - game.runtime() / 250
    log = sprites.createProjectileFromSide(img`
        ........................
        ..........bbbb..........
        ........bbddddbb........
        .......bddbbbbddb.......
        ......bdbbddddbbdb......
        .....bdbbdbbbbdbbdb.....
        .....bdbdbddddbdbdb.....
        .....cdbbdbbbbdbbdc.....
        .....cbdbbddddbbdbc.....
        .....efbddbbbbddbce.....
        .....eeffbddddbccee.....
        .....eeeeffcccceee......
        .....ceeeeeeeeeeee......
        .....ceeeeeeeeeeee......
        .....feeeeeeeeeeee......
        .....cceeeeeeeeeee......
        ......feeeeeeeeeee......
        .....6fceeeeeeeeee6.....
        ....6776eeeeeeeee676....
        ...6777666eeee6666776...
        ..67768e67766777667776..
        ...668ee7768867788666...
        ......ee77eeee77ecee....
        ......ee6eeeeee6eef.....
        `, log_speed, 0)
    log.y = 80
    info.changeScoreBy(10)
})
